### ISSUE TITLE
Potential vulnerabilities due to PR 18

### ISSUE THREAD

**Issue by lxylxy123456** [superymk/xmhf64#23]
I recently reviewed [PR 18](https://github.com/superymk/xmhf64/pull/18/files) and found the following potential vulnerabilities.

1. SL does not check `slpb.runtime_bss_high_base == rpb->XtVmmRuntimeBSSHighBegin`. It also does not check `slpb.runtime_bss_high_size == XMHF_RUNTIME_LARGE_BSS_DATA_SIZE`
2. SL does not check that the runtime bss high memory is full of zero. It also does not memset this memory with zero.
3. SL does not check that `[rpb->XtVmmRuntimeBSSHighBegin, rpb->XtVmmRuntimeBSSHighBegin + XMHF_RUNTIME_LARGE_BSS_DATA_SIZE)` and `[rpb->XtVmmRuntimePhysBase, rpb->XtVmmRuntimePhysBase + rpb->XtVmmRuntimeSize)` do not overlap. (i.e. attacker can make run time high bss and other part of runtime overlap).

Please consider fixing them, thank you!

**Comment by superymk** [comment]
Thanks for reporting the issues! They are fixed in 653da2d and 40a39f0
