### ISSUE TITLE
Alignment question in sl.lds.S

### ISSUE THREAD

**Issue by lxylxy123456** [superymk/xmhf64#8]
Why is this aligned to 0x10000 (16 * 4096) instead of 4096?
https://github.com/superymk/xmhf64/blob/aafdb9af149dfa4798c6851f53935fe052693320/xmhf/src/xmhf-core/xmhf-secureloader/sl.lds.S#L113

**Comment by superymk** [comment]
Thanks! I used it as another way to ensure the rodata section does not cross the 64KB boundary. Yes, it can be removed.

**Comment by lxylxy123456** [comment]
Created https://github.com/superymk/xmhf64/pull/10

**Comment by superymk** [comment]
Fixed in e28791dac
